image:
  file: .gitpod.Dockerfile

tasks:
  - name: Java & Gradle 
    command: | 
      sdk current
    openMode: split-left
  - name: Time zone
    command: | 
      date
    openMode: split-right


